import { Box, Heading, SimpleGrid } from '@chakra-ui/react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Card from '../components/Card'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { ColorModeSwitcher } from "../components/ColorModeSwitcher";
import OverviewFlow from '../OverviewFlow'


const Home: NextPage = () => {
  return (

    <OverviewFlow />

    /* <div className={styles.container}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ColorModeSwitcher />

        <Heading>Project Management Tools</Heading>

        <SimpleGrid columns={1} spacing={5}>
          <Link href="/tools/pert">
            <Card title='Project Evaluation and Review Technique (PERT)' description='PERT is a visual project management tool used to map out and track the tasks and timelines.' />
          </Link>
        </SimpleGrid>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://github.com/aymantaybi"
          target="_blank"
          rel="noopener noreferrer"
        >
          Made with ❤️ by&nbsp;
          <b>
            aymantaybi
          </b>
        </a>
      </footer>
    </div> */

  )
}

export default Home
